extra_stopwords = [
    'python', 'speaker', 'speakers', 'dublin', 'ireland', 'pyladies',
    'talk', 'talks', 'irish', 'james', 'julie', 'leticia', 'charlie',
    'michael', 'marjai', 'atmasked', 'masked', 'isabella', 'annie',
    'lowney', 'daire', 'amaral', 'carlos', 'campbell', 'chris', 
    'docherty', 'louise', 'deepali', 'andrea', 'diarmuid', 'sorcha',
    'jonathan', 'eamon', 'shane', 'stella', 'mclennan', 'ingrid',
    'aimi', 'niamh', 'forgan', 'jans', 'sabine', 'vicky', 'ariane',
    'kats', 'bourke', 'georges', 'frances', 'heres', 'donnelly', 
    'lia', 'thanks', 'per', 'simon', 'maybe', 'else', 'joanna', 
    'guy', 'piotr', 'milian', 'mccluskey', 'irelands', 'twomey',
    'máté', 'serena', 'actually', 'mick', 'mansura', 'mihai', 
    'atmaske', 'mark', 'hiroki', 'claire', 'yvonne', 'franciscos',
    'mask', 'annie', 'lowney', 'grace', 'vickymasked', 'cheryl',
    'demonware', 'pyladiesdub', 'aon', 'demonware', 'lala', 'august',
    'october', 'cheryl', 'july', 'goodreads', 'parking', 'boigrandcanalsq', 
    'doesnt', 'aol', 'barge', 'see', 'luas', 'dock', 'qualtrics', 'pepper',
    'twisted', 'happening', 'keep', 'november', 'sponsoring', 'organisers', 
    'happened', 'sept', 'probably', 'indeedcom', 'notice', 'around', 'lets',
    'september', 'thank', 'rte', 'november', 'dit', 'april', 'anyone', 
    'outside', 'anything', 'upstairs', 'near', 'marjaicoder', 'intercom',
    'facebook', 'venue', 'youand', 'notedont', 'back', 'night', 'suggestion', 
    'using', 'comment', 'questions', 'event', 'please', 'use', 'wasnt', 'ago',
    'answer', 'doonnybrook', 'rté', 'mentorsinterested', 'nutley', 'may', 
    'suggestions', 'grad', 'round', 'gordan', 'microsoft', 'bank', 'whoop',
    'grand', 'groupon', 'workdays', 'dublins', 'rsvping', 'underlining', 'tba'
    'announce', 'content', 'kevin', 'irene',  'dbs', 'oneday', 'bitbuzz', 'ics',
    'ict', 'comments', 'talksfeel', 'advertisingcom', 'meiling', 'apologies', 'let', 
    'yard', 'attending', 'fa', 'round', 'demanding', 'le', 'glasgow', 'want',
    'continuing', 'meantime', 'depending', 'step', 'closed', 'gallery', 'available',
    'sure', 'right', 'giving', 'every', 'way', 'faq', 'shout', 'ill', 'set', 'thats',
    'stuff', 'contact', 'via', 'leave', 'rough', 'first', 'fiona', 'sonia', 'theres',
    'giving', 'awesome', 'become', 'title', 'afterwards', 'becomes', 'visiting', 'leave',
    'habiba', 'ballsbridge', 'workday', 'means', 'come', 'whos', 'tcds', 'whitehot', 
    'sciencegallerycom', 'dogpatch', 'stilll', 'ran', 'door', 'arriving', 'short', 'next',
    'etc', 'month', 'suitable', 's[eaking', 'forget', 'interested', 'ok', 'last', 'get', 'feb',
    'find', 'optional', 'far', 'galligan', 'missed', 'final', 'rsvp', 'cannot', 'open', 
    'nice', 'anywhere', 'solve', 'suzanne', 'female', 'summit', 'womens', 'max'
]